#!/bin/bash

################################################################################
# Forge API Monitoring - Systemd Service Setup
#
# This script sets up the Forge monitoring system as a systemd service
# for continuous monitoring on Linux systems.
#
# Usage:
#   sudo bash setup-forge-monitoring-systemd.sh
#
################################################################################

set -euo pipefail

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly RESET='\033[0m'

print_info() {
    echo -e "${BLUE}[INFO]${RESET} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${RESET} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${RESET} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${RESET} $1"
}

require_root() {
    if [ "$EUID" -ne 0 ]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

get_config() {
    print_info "Gathering configuration..."

    # Get project directory
    read -rp "Project directory (e.g., /home/user/project): " PROJECT_DIR
    if [ ! -d "$PROJECT_DIR" ]; then
        print_error "Directory not found: $PROJECT_DIR"
        exit 1
    fi

    # Check scripts directory
    if [ ! -f "$PROJECT_DIR/scripts/monitor-via-api.sh" ]; then
        print_error "monitor-via-api.sh not found in $PROJECT_DIR/scripts"
        exit 1
    fi

    # Get Forge API token
    read -rsp "Forge API Token: " FORGE_API_TOKEN
    echo ""

    # Get Server ID
    read -rp "Forge Server ID: " FORGE_SERVER_ID

    # Get service user
    read -rp "Service user (default: www-data): " SERVICE_USER
    SERVICE_USER="${SERVICE_USER:-www-data}"

    # Check if user exists
    if ! id "$SERVICE_USER" &>/dev/null; then
        print_warning "User '$SERVICE_USER' does not exist"
        read -rp "Create user? (y/n): " -n 1 CREATE_USER
        echo ""
        if [[ $CREATE_USER == [Yy] ]]; then
            useradd -r -s /bin/bash "$SERVICE_USER" 2>/dev/null || true
            print_success "User created: $SERVICE_USER"
        else
            print_error "User not found: $SERVICE_USER"
            exit 1
        fi
    fi

    # Get log directory
    read -rp "Log directory (default: /var/log/forge-monitor): " LOG_DIR
    LOG_DIR="${LOG_DIR:-/var/log/forge-monitor}"

    # Get Slack webhook (optional)
    read -rp "Slack webhook URL (optional, leave blank to skip): " SLACK_WEBHOOK

    # Get monitoring interval
    read -rp "Polling interval in seconds (default: 30): " POLLING_INTERVAL
    POLLING_INTERVAL="${POLLING_INTERVAL:-30}"

    # Get refresh rate
    read -rp "Dashboard refresh rate in seconds (default: 5): " REFRESH_RATE
    REFRESH_RATE="${REFRESH_RATE:-5}"
}

create_env_file() {
    print_info "Creating environment file..."

    ENV_FILE="$PROJECT_DIR/.env.forge-monitor"

    cat > "$ENV_FILE" <<EOF
# Forge API Monitoring Configuration
# Generated by setup-forge-monitoring-systemd.sh

FORGE_API_TOKEN="$FORGE_API_TOKEN"
FORGE_SERVER_ID="$FORGE_SERVER_ID"
FORGE_API_BASE="https://forge.laravel.com/api/v1"

# Monitoring Configuration
MONITOR_THRESHOLD_CPU=80
MONITOR_THRESHOLD_MEM=85
MONITOR_THRESHOLD_DISK=90

# Slack Integration (optional)
SLACK_WEBHOOK="${SLACK_WEBHOOK}"

# Logging
LOG_DIR="$LOG_DIR"
POLLING_INTERVAL="$POLLING_INTERVAL"
REFRESH_RATE="$REFRESH_RATE"
EOF

    chmod 600 "$ENV_FILE"
    print_success "Environment file created: $ENV_FILE"
    print_warning "Keep this file secure - it contains your API token!"
}

create_systemd_service() {
    print_info "Creating systemd service..."

    SERVICE_FILE="/etc/systemd/system/forge-monitor.service"

    cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Forge API Real-Time Monitoring Service
Documentation=file://$PROJECT_DIR/scripts/README-FORGE-API.md
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$PROJECT_DIR
EnvironmentFile=$PROJECT_DIR/.env.forge-monitor

ExecStart=$PROJECT_DIR/scripts/monitor-via-api.sh \\
  --log $LOG_DIR/monitor.log \\
  --interval \$POLLING_INTERVAL \\
  --refresh-rate \$REFRESH_RATE\\
  --slack-webhook "\$SLACK_WEBHOOK"

# Process management
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal
SyslogIdentifier=forge-monitor

# Resource limits
MemoryLimit=256M
CPUQuota=50%

# Security
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=$LOG_DIR

[Install]
WantedBy=multi-user.target
EOF

    chmod 644 "$SERVICE_FILE"
    print_success "Service file created: $SERVICE_FILE"
}

create_log_directory() {
    print_info "Creating log directory..."

    mkdir -p "$LOG_DIR"
    chown "$SERVICE_USER:$SERVICE_USER" "$LOG_DIR"
    chmod 755 "$LOG_DIR"

    print_success "Log directory created: $LOG_DIR"
}

create_rotate_config() {
    print_info "Creating logrotate configuration..."

    ROTATE_FILE="/etc/logrotate.d/forge-monitor"

    cat > "$ROTATE_FILE" <<EOF
$LOG_DIR/monitor.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0640 $SERVICE_USER $SERVICE_USER
    sharedscripts
    postrotate
        systemctl reload forge-monitor > /dev/null 2>&1 || true
    endscript
}
EOF

    chmod 644 "$ROTATE_FILE"
    print_success "Logrotate configuration created: $ROTATE_FILE"
}

create_monitoring_script() {
    print_info "Creating monitoring check script..."

    CHECK_SCRIPT="$PROJECT_DIR/scripts/check-forge-monitor.sh"

    cat > "$CHECK_SCRIPT" <<'EOF'
#!/bin/bash
# Check if Forge monitoring service is running and healthy

SERVICE_NAME="forge-monitor"
LOG_FILE="/var/log/forge-monitor/monitor.log"
TIMEOUT_SECONDS=300  # 5 minutes

# Check if service is active
if ! systemctl is-active --quiet "$SERVICE_NAME"; then
    echo "CRITICAL: Service $SERVICE_NAME is not running"
    exit 2
fi

# Check if service is enabled
if ! systemctl is-enabled --quiet "$SERVICE_NAME"; then
    echo "WARNING: Service $SERVICE_NAME is not enabled"
    exit 1
fi

# Check if log file exists and is being updated
if [ ! -f "$LOG_FILE" ]; then
    echo "CRITICAL: Log file not found: $LOG_FILE"
    exit 2
fi

# Check log file modification time
LAST_MODIFIED=$(stat -c %Y "$LOG_FILE")
CURRENT_TIME=$(date +%s)
TIME_DIFF=$((CURRENT_TIME - LAST_MODIFIED))

if [ $TIME_DIFF -gt $TIMEOUT_SECONDS ]; then
    echo "CRITICAL: Log file not updated for ${TIME_DIFF}s (timeout: ${TIMEOUT_SECONDS}s)"
    exit 2
fi

# Check for recent errors in log
if tail -100 "$LOG_FILE" | grep -qi "error\|critical"; then
    echo "WARNING: Recent errors found in log file"
    tail -5 "$LOG_FILE"
    exit 1
fi

echo "OK: Forge monitoring service is healthy"
exit 0
EOF

    chmod 755 "$CHECK_SCRIPT"
    print_success "Health check script created: $CHECK_SCRIPT"
}

create_dashboard_script() {
    print_info "Creating dashboard view script..."

    DASHBOARD_SCRIPT="$PROJECT_DIR/scripts/forge-dashboard.sh"

    cat > "$DASHBOARD_SCRIPT" <<'EOF'
#!/bin/bash
# View Forge monitoring dashboard

SERVICE_NAME="forge-monitor"
LOG_FILE="/var/log/forge-monitor/monitor.log"

echo "Forge API Monitoring Dashboard"
echo "==============================="
echo ""

echo "Service Status:"
systemctl status "$SERVICE_NAME" --no-pager | head -5
echo ""

echo "Recent Activity:"
tail -20 "$LOG_FILE"
echo ""

echo "Latest Metrics:"
ls -lht /tmp/forge_metrics_cache.json 2>/dev/null || echo "No metrics cache found"
EOF

    chmod 755 "$DASHBOARD_SCRIPT"
    print_success "Dashboard script created: $DASHBOARD_SCRIPT"
}

reload_systemd() {
    print_info "Reloading systemd daemon..."
    systemctl daemon-reload
    print_success "Systemd daemon reloaded"
}

enable_and_start_service() {
    print_info "Enabling and starting service..."

    systemctl enable forge-monitor
    systemctl start forge-monitor

    print_success "Service enabled and started"
}

show_status() {
    print_info "Service status:"
    echo ""
    systemctl status forge-monitor --no-pager
}

show_logs() {
    print_info "Recent logs:"
    echo ""
    journalctl -u forge-monitor -n 20 --no-pager
}

show_summary() {
    cat << EOF

${GREEN}╔════════════════════════════════════════════════════════════════╗${RESET}
${GREEN}║         FORGE MONITORING SETUP COMPLETE                        ║${RESET}
${GREEN}╚════════════════════════════════════════════════════════════════╝${RESET}

Configuration Summary:
${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Project Directory:     $PROJECT_DIR
Service User:         $SERVICE_USER
Log Directory:        $LOG_DIR
Environment File:     $PROJECT_DIR/.env.forge-monitor
Service File:         /etc/systemd/system/forge-monitor.service

${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Useful Commands:
${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Start monitoring service:
  ${YELLOW}sudo systemctl start forge-monitor${RESET}

Stop monitoring service:
  ${YELLOW}sudo systemctl stop forge-monitor${RESET}

View service logs:
  ${YELLOW}sudo journalctl -u forge-monitor -f${RESET}

View monitoring dashboard:
  ${YELLOW}$PROJECT_DIR/scripts/forge-dashboard.sh${RESET}

Check service health:
  ${YELLOW}$PROJECT_DIR/scripts/check-forge-monitor.sh${RESET}

View service status:
  ${YELLOW}sudo systemctl status forge-monitor${RESET}

Enable/disable service:
  ${YELLOW}sudo systemctl enable forge-monitor${RESET}
  ${YELLOW}sudo systemctl disable forge-monitor${RESET}

View environment configuration:
  ${YELLOW}cat $PROJECT_DIR/.env.forge-monitor${RESET}

${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Security Notes:
${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

1. Environment file contains API tokens
   Location: $PROJECT_DIR/.env.forge-monitor
   Permissions: 600 (owner read/write only)
   ${YELLOW}NEVER commit this file to version control${RESET}

2. Add to .gitignore:
   ${YELLOW}echo '.env.forge-monitor' >> $PROJECT_DIR/.gitignore${RESET}

3. Monitor log files are protected:
   Location: $LOG_DIR
   Permissions: 755 (system readable)
   Rotation: 30 days daily

4. Service runs as: ${YELLOW}$SERVICE_USER${RESET}

${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

Next Steps:
${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

1. View current status:
   ${YELLOW}sudo systemctl status forge-monitor${RESET}

2. Watch logs in real-time:
   ${YELLOW}sudo journalctl -u forge-monitor -f${RESET}

3. Test deployment monitoring:
   ${YELLOW}cd $PROJECT_DIR && ./scripts/forge-monitoring-examples.sh 1${RESET}

4. Set up Nagios/Icinga integration:
   ${YELLOW}$PROJECT_DIR/scripts/check-forge-monitor.sh${RESET}

5. View comprehensive documentation:
   ${YELLOW}cat $PROJECT_DIR/scripts/README-FORGE-API.md${RESET}
   ${YELLOW}cat $PROJECT_DIR/scripts/FORGE-MONITORING-GUIDE.md${RESET}

${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}

EOF
}

main() {
    echo ""
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${RESET}"
    echo -e "${BLUE}║  Forge API Monitoring - Systemd Service Setup              ║${RESET}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${RESET}"
    echo ""

    require_root
    get_config
    create_env_file
    create_log_directory
    create_systemd_service
    create_rotate_config
    create_monitoring_script
    create_dashboard_script
    reload_systemd
    enable_and_start_service

    sleep 2

    show_status
    echo ""
    show_logs
    echo ""
    show_summary
}

main "$@"
